### PR TITLE
Resolut: Failed to concat aac files

### PR DESCRIPTION
**Pull request by poccariswet**
#20 Maybe ffmpeg is not able to concat aac files if the aac files include 'ID3 tag', so I got rid of ID3 tags in aac files. And remake the aac files is not included the tag.

---
This change is [Reviewable](https://reviewable.io/reviews/yyoshiki41/radigo/23)

### CODE REVIEW

**Comment by yyoshiki41** [comment]
Hi, @soeyusuke 

Thanks to you, I learned about  'ID3 tag' for the first time!
I tried your branch in my environment but https://github.com/yyoshiki41/radigo/issues/20 does not resolved.

## In my case

```
$ ffmpeg --version
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.37)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma

$ go run ./cmd/radigo/main.go rec -id=LFR -s=20180107010000
Now downloading..
/
+------------+----------------------------------+
| STATION ID |              TITLE               |
+------------+----------------------------------+
| LFR        | オードリーのオールナイトニッポン |
+------------+----------------------------------+
| Completed!
/tmp/radigo/output/20180107010000-LFR.aac
```

And output aac file is 5 sec duration.
Please let me know if there is something wrong or missing.

---

I reviewed this pr and learned many things in your code.
Thanks!

**Comment by poccariswet** [comment]
Oh,,, sorry. I missed to confirm the work, so I'll find how to solve once again.

**Comment by poccariswet** [comment]
Hi, @yyoshiki41 . I tried the issue #20 again.
This commit is solved the #20 issue. If you are free, please try.

**Comment by yyoshiki41** [comment]
@soeyusuke 
I checked #20 was fixed 👍 

Thanks for your try many times!

**Pull request merged**
